### ISSUE TITLE
unable to install requirement

### ISSUE THREAD

**Issue by ramubonkuri** [aiplanethub/genai-stack#41]
* GenAI Stack version: 
* Python version:3.6
* Operating System:windows

### Description

Trying to install required libs from ui/requiremts.txt but getting version related issues

ERROR: Could not find a version that satisfies the requirement attrs==23.1.0 (from -r requirements.txt (line 2)) (from versions: 15.0.0a1, 15.0.0, 15.1.0, 15.2.0, 16.0.0, 16.1.0, 16.2.0, 16.3.0, 17.1.0, 17.2.0, 17.3.0, 17.4.0, 18.1.0, 18.2.0, 19.1.0, 19.2.0, 19.3.0, 20.1.0, 20.2.0, 20.3.0, 21.1.0, 21.2.0, 21.3.0, 21.4.0, 22.1.0, 22.2.0)
ERROR: No matching distribution found for attrs==23.1.0 (from -r requirements.txt (line 2))

ERROR: Could not find a version that satisfies the requirement blinker==1.6.2 (from -r requirements.txt (line 3)) (from versions: 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5)
ERROR: No matching distribution found for blinker==1.6.2 (from -r requirements.txt (line 3))

### What I Did
pip install -r requirements.txt

if we remove the version, it is installing

**Comment by shreehari-aiplanet** [comment]
@ramubonkuri  thanks for reaching out. Good to know that you were about find a work around by updating the version.
 We kindly recommend using Python version 3.8 or higher, this would ensure the enough compatibility.

**Comment by shreehari-aiplanet** [comment]
@ramubonkuri Closing this issue assuming its resolved. Feel free to re-open if you further help.
Thanks
