### ISSUE TITLE
[Component] Adding YouTube Langchain Loader feature

### ISSUE THREAD

**Issue by jaintarunAI** [aiplanethub/genai-stack#54]
* GenAI Stack version: 0.2.0
* Python version: 3.8+

### Hacktoberfest Accepted PR guidelines

- Please check the documentation and CONTRIBUTING.md before you start making changes
- We accept the PR as `hacktoberfest-accepted` for this issue, if the PR adds the support of YouTube Video loaders in ETL.

**Comment by shreehari-aiplanet** [comment]
Moved to https://github.com/aiplanethub/genai-stack/issues/55
