### ISSUE TITLE
Caching Improvement - Not able to differentiate keywords between distinct sentences

### ISSUE THREAD

**Issue by sam-aiplanet** [aiplanethub/genai-stack#91]
There are a couple of edge cases that we want to tackle in the caching layer.

**Comment by plaban1981** [comment]
![image](https://github.com/aiplanethub/genai-stack/assets/23618329/616d19c4-1ead-44f0-9065-fe16687b7249)

Question : What is the early stage grants for Key Developer or Engineer in ESOP allocation ?
Response : the early stage grants for a Key Developer or Engineer in ESOP allocation are typically 1-2%.'

Question: What is the early stage grants for CTO in ESOP allocation ?
Response: the early stage grants for a Key Developer or Engineer in ESOP allocation are typically 1-2%.'

For both the above questions the response is same as the the genaistack caching logic understands both the questions to be semantically same. But in actual the first question is intended for Key Developer while the second question is intended for the CTO
